# Generated by Django 4.2.4 on 2023-08-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosecha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
        ),
    ]
