# Generated by Django 4.2.4 on 2023-08-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosecha', '0005_fasecultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
            ],
        ),
    ]
