# Generated by Django 4.2.4 on 2023-08-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosecha', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('cantidad_cosechada', models.PositiveIntegerField()),
                ('equipo_utilizado', models.CharField(max_length=100)),
                ('calidad_cosechado', models.CharField(max_length=20)),
                ('observaciones', models.TextField()),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosecha.fasecultivo')),
                ('persona_ejecuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosecha.user')),
                ('tipo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosecha.tipodecultivo')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosecha.variedade')),
            ],
        ),
    ]
