# Generated by Django 4.2.4 on 2023-08-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosecha', '0008_remove_cosecha_tipo_cultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('tipo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosecha.tipodecultivo')),
            ],
        ),
    ]
