# Generated by Django 4.2.4 on 2023-08-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosecha', '0009_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='cultivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cosecha.cultivo'),
        ),
    ]
