# Generated by Django 4.2.4 on 2023-08-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosecha', '0010_cosecha_cultivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosecha',
            name='persona_ejecuta',
        ),
    ]
