# Generated by Django 4.2.4 on 2023-08-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosecha', '0011_remove_cosecha_persona_ejecuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='persona_ejecuta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cosecha.user'),
        ),
    ]
