# Generated by Django 4.2.4 on 2023-08-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosecha', '0012_cosecha_persona_ejecuta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Colaborador',
        ),
    ]
